name: Build-OpenWrt-luci-app-softethervpn

on:
  #push:
  workflow_dispatch:
    inputs:
      tag:
        description: '请填写发布Releases的版本号（留空不发布）'
        required: false
        default: ''
      text:
        description: '请填写发布的说明'
        required: false
        default: ''
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
env:
  TAG: "${{ github.event.inputs.tag }}"
  TZ: Asia/Shanghai
permissions:
  contents: write
jobs:
  build:
    name: Build ${{ matrix.arch }}-${{ matrix.sdk }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        arch:
          # - aarch64_cortex-a53
          # - aarch64_cortex-a72
          # - aarch64_generic
          # - arm_arm1176jzf-s_vfp
          # - arm_arm926ej-s
          # - arm_cortex-a15_neon-vfpv4
          # - arm_cortex-a5_vfpv4
          # - arm_cortex-a7
          # - arm_cortex-a7_neon-vfpv4
          # - arm_cortex-a8_vfpv3
          # - arm_cortex-a9
          # - arm_cortex-a9_neon
          # - arm_cortex-a9_vfpv3-d16
          # - arm_fa526
          # #- arm_mpcore
          # - arm_xscale
          # - mips_24kc
          # #- mips_4kec
          # - mips_mips32
          # - mipsel_24kc
          # - mipsel_24kc_24kf
          # - mipsel_74kc
          # - mipsel_mips32
          - x86_64
          
        sdk:
          - 22.03.7
          - SNAPSHOT

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Cache OpenWrt SDK
        uses: actions/cache@v4
        with:
          path: |
            /opt/openwrt-sdk-${{ matrix.arch }}-${{ matrix.sdk }}
            dl
          key: sdk-${{ matrix.arch }}-${{ matrix.sdk }}
          
      # - name: Overwrite i18n file
      #   run: |
      #     cat > luci-app-luci-app-softethervpn/root/etc/uci-defaults/luci-i18n-luci-app-softethervpn-zh-cn << 'EOF'
      #     #!/bin/sh
      #     exit 0
      #     EOF
          
      - name: Building packages
        uses: openwrt/gh-action-sdk@main
        env:
          ARCH: ${{ matrix.arch }}-${{ matrix.sdk }}
          FEEDNAME: packages_ci
          PACKAGES: luci-app-softethervpn
          #NO_DEFAULT_FEEDS: 1
          NO_REFRESH_CHECK: 1
          NO_SHFMT_CHECK: 1
          MAKEFLAGS: -j$(nproc)
          V: s

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: luci-app-softethervpn-${{ matrix.arch }}-${{ matrix.sdk }}
          path: bin/packages/${{ matrix.arch }}/packages_ci/

            # 将 “Create compress files” 步骤重命名为更贴切的 “Prepare for Release”
      - name: Prepare for Release
        run: |
          sudo timedatectl set-timezone "Asia/Shanghai"
          echo "build_time=$(TZ=UTC-8 date '+%Y年%m月%d日%H:%M:%S' | jq -sRr @uri)" >> $GITHUB_ENV
          # 进入编译输出目录
          cd bin/packages/${{ matrix.arch }}/packages_ci
          # 关键：使用模式匹配，仅复制目标包的文件
          # 此模式匹配所有以 "easytier" 或 "luci-app-easytier" 开头的 .ipk 或 .apk 文件
          cp -v *softethervpn*.{ipk,apk} $GITHUB_WORKSPACE/ || true
          # 返回工作空间根目录
          cd $GITHUB_WORKSPACE

      - name: Release
        if: ${{ github.event.inputs.tag != '' }}
        uses: softprops/action-gh-release@v2
        with:
            token: ${{ secrets.GITHUB_TOKEN }}
            body: |

             > ### ![](https://img.shields.io/badge/%E7%BC%96%E8%AF%91%E6%97%B6%E9%97%B4-${{ env.build_time }}-easyTier?logo=github&labelColor=%E9%A1%BB)![](https://img.shields.io/github/downloads/${{ github.repository }}/${{ env.TAG }}/total?label=%E4%B8%8B%E8%BD%BD%E6%AC%A1%E6%95%B0&logo=github)

             - 其中 **`22.03.7`** 里面是ipk安装包 **`SNAPSHOT`** 里面是apk安装包

             - **`*.apk` 是OpenWrt新版的APK包** 对于apk包跳过证书命令
             `apk add --allow-untrusted luci-app-softethervpn.apk`

             ${{ github.event.inputs.text }}
           
            tag_name: ${{ env.TAG }}
            # 直接发布所有找到的 .ipk 和 .apk 文件
            files: |
              *softethervpn*.ipk
              *softethervpn*.apk
              
 
